
const proverbs = ['A burning light may go out, a sailing man may drown.',
"A child's grief is soon put out.", 
'A fair wind at our back is best.',
'A grey patch is better than a bare side.', 
'A tied dog does not jump farther than his cord.',
'A tied up man is sorrowful.',
'Age is nothing to boast of; you get it for nothing.', 
'Age probably leads to something worse.',
'All birds cannot be hawks (some are just cuckoos).', 
'All birds cannot be hawks.', 
"All don't like the same thing; some like it cold, and some like it hot.",
'All food does not come upon one single dish.',
'All madmen are not the same.',
'All masters are born, but none is born a master except the billygoat',
'All sense is not housed in one single head.',
'All shoes are not sewn on the same last.',
'All the fat floats together.',
"Another's horse is always strong.",
"Another's steak is always fat.",
'Away is not to be at home.',
'Bare are buttocks without breaches.',
'Barter is for fault.',
'Barter is to favour two and not just one.',
'Best that vende mens it goes vel.',
'Better (be) aware beforehand than quick afterwards.',
'Better (be) wise beforehand than aware afterwards.',
'Better (be) wise beforehand than wise afterwards (after the damage or accident).',
'Better a whole ship than a broken one.',
'Better an empty purse than wrongly got money.',
'Better barefooted than without jeans.',
'Better be limping than footless.', 
'Better be unmarried than badly married.',
'Better be without money than without honor.',
'Better let ten guilty ones go free than judging an innocent man.', 
'Better lie uncomfortably than to cover oneself with a rag.', 
'Better little than nothing.', 
'Better ten hairs on the head than one in the soup.', 
'Better to live with certainty than in the hope.', 
'Better too full than too early empty (about stores).', 
'Better turn in the brook than in the waterfall.', 
'Better turn than go astray.', 
'Better unlearned and bright than erudite and foolish.', 
'Better whole than mended well (probably).', 
'Beyond the mountain there are people too.', 
'Blind hen finds a corn too.', 
"Blindest is he who doesn't want to see.",
'Boatless man is tied to the land.', 
'Bookless man is (quite) blind.', 
'Bookless man may struggle badly.', 
'Both gentlemen and fools speak freely.', 
'Certainty is better than hope. Better sit with certainty than walk with hope.', 
'Child memories will last long.', 
'Children are pauper wealth.', 
"Children do children's work.", 
'Documents do not forget.', 
'Either conform to the customs or flee the country.', 
'Even the best horse may stumble.', 
'Even the best swimmer may sink.', 
'Everybody looks at others, and none on himself.', 
'Everybody wants to put the axe in the bear-skull, but nobody wants to hold the handle.', 
'Everyone has seen his cradle, but none his grave.', 
'Everyone knows what to do with a bad (crazy) wife except the one who has her.', 
'Everyone wants to climb the lowest fence.', 
'Everyone wants to hear praise, and nobody blame.',
'Everyone would rather hear praise than blame.', 
'Everyone wants to live long, but nobody wants to age (get old).', 
'Everyone wants to turn the prettiest side forward.', 
"Everyone's friend is faithful to none.", 
'Everything does not go as we guess.', 
'Everything has an end, except the sausage, she has two.', 
'Everything is good for its own use.', 
'Everything is not as bad as it sounds.', 
'Everything is pure to the pure.', 
'Everything is well told that is well received.', 
'Everything must be destroyed that is meant to be so.', 
'Everything needs its time.', 
'Everything serves the thief.', 
'Everything will lie where it is lowest.', 
'Face to face eagles shall claw (fight).', 
'Farmer thrives among farmers best.', 
'From a gruff word both harm and murder may ensue.', 
'From children and drunk people we get to hear the truth.', 
'From harm one gets wise (and not rich).', 
'From nothing comes nothing.', 
'From our years we learn more than from many books.', 
'From small seeds big trees grow.', 
'Getting a small part is better than a long quarrel.', 
'Good love glides easily and smoothly and pays in time.', 
'Great fear and spanking hardly make the boy extremely wise.', 
'Honor the old, teach the young.', 
'If the man does not heed time, time does not heed the man.', 
'If you bend the bow too much, it will break.', 
'If you bend the rights, they will break.', 
'If you build your house as everybody counsels, it will never stand straight.', 
'It is easier to learn from the damage of another.', 
"It's best to stop while things go well.", 
'Merely book makes none wise.', 
'Most prayers go unanswered anyway.', 
'Not everyone can become pope in Rome.', 
'Not everyone can have the bishop for his uncle.', 
"Not everyone can meet one's better." ]

const proverb_length = proverbs.length;

let pickRandomProverb = function(){
	let random_num = Math.floor(Math.random() * proverb_length);
	return proverbs[random_num];
}



